server {
	listen 8080;
	client_max_body_size 10M;

	location /cgi-bin {
		methods GET POST;
		root ./var/www/cgi-bin;
		autoindex off;
		index index.cgi;
		cgi .py /usr/bin/python3 ./var/www/cgi-bin;
	}
	
	location / {
		methods GET POST DELETE;
		root ./var/www/html;
		index index.html;
		autoindex off;
	}
}
