
	server {
		listen 8080;
		client_max_body_size 10M;

		error_page 404 ./var/www/errors/404.html;
		error_page 500 ./var/www/errors/500.html;
		error_page 403 ./var/www/errors/403.html;

		location / {
			methods GET;

			root ./var/www/html;
			index index.html;

			autoindex off;

			# upload off;
		}

		location /autoindex {
			methods GET;

			root ./var/www/;
			autoindex on;
		}

		location /hollow {
			methods GET;

			root ./var/www/;

			autoindex off;

			index index.html;
		}

		location /hollow2 {
			methods GET;

			root ./var/www/;

			autoindex off;

			index index.html;
		}

		location /pong {
			methods GET;

			root ./var/www/;

			autoindex off;

			index pong.html;
		}

		location /upload {
			methods POST;

			root ./var/www/;

			autoindex off;

			index index.html;

			# upload on;
			# upload_store ./var/www/uploads;
		}

		location /old-page {
			methods GET;

			return 301 /;
		}

		location /cgi-bin {
			methods GET POST;

			root ./var/www/cgi-bin;

			autoindex off;

			index index.cgi;

			# cgi_extension .cgi;
			# cgi_path /usr/bin/python3;
		}
	}

